# -*- coding: utf-8 -*-
"""CAPSTONE (ML).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wvv9pjcZyck7x75CEBqU6hwgW-96xSg4
"""

import os
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report,confusion_matrix,roc_auc_score,f1_score
from xgboost import XGBClassifier
from imblearn.over_sampling import SMOTE

#Ensure output directory exists for presentation visuals
os.makedirs('plots', exist_ok=True)

#1. DATA INGESTION AND CLEANING
print("-"*65)
print(f"\033[1m{'LOADING AND CLEANING DATA':^50}\033[0m")
df= pd.read_csv('predictive_maintenance.csv')

#Standardize column names to remove units and speacial characters
df.columns=[
    'UDI','Product ID','Type','Air temperature','Process temperature',
    'Rotational speed','Torque','Tool wear','Target','Failure Type'
]

#Drop unique identifiers and secondary targets to prevent data leakage
X= df.drop(columns=['UDI','Product ID','Target','Failure Type'])
y= df['Target']

#Convert categorial 'Type' feature (L,M,H) to binary flags
X= pd.get_dummies(X, columns=['Type'], drop_first=True)
print(f"-> DATASET SHAPE:{X.shape}")
print(f"-> CLASS DISTRIBUTION BEFORE SMOTE:{np.bincount(y)} (Healthy Vs Failed)\n")

# 2. TRAIN TEST SPLIT & FEATURE SCALING
X_train, X_test, y_train, y_test= train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
scaler= StandardScaler()
X_train_scaled= scaler.fit_transform(X_train)
X_test_scaled= scaler.transform(X_test)

# 3. HANDLING CLASS IMBALANCE
print("-"*65)
print(f"\033[1m{'APPLYING SMOTE TO BALANCE DATASET':^50}\033[0m")
smote=SMOTE(random_state=42)
X_train_resampled, y_train_resampled= smote.fit_resample(X_train_scaled, y_train)
print(f"-> CLASS DISTRIBUTION AFTER SMOTE:{np.bincount(y_train_resampled)}\n")

# 4. MODEL TRAINING (XGBOOST CLASSIFIER)
model= XGBClassifier(
    n_estimators=100,
    max_depth=5,
    learning_rate=0.1,
    random_state=42,
    eval_metric='logloss'
)
model.fit(X_train_resampled, y_train_resampled)

# 5. EVALUATION & METRICS GENERATION
print("-"*65)
print(f"\033[1m{'EVALUATING MODEL PERFORMANCE':^50}\033[0m")
y_pred= model.predict(X_test_scaled)
y_pred_proba= model.predict_proba(X_test_scaled)[:,1]

#Test reports for written project
print("-> CONFUSION MATRIX")
cm= confusion_matrix(y_test, y_pred)
print(cm)
print("\n-> CLASSIFICATION REPORT")
print(classification_report(y_test,y_pred,target_names=['Healthy','Failure']))
roc_auc= roc_auc_score(y_test, y_pred_proba)
print(f"-> ROC-AOC SCORE:{roc_auc:.4f}\n")

# 6. VISUALIZATION GENERATION
# Confusion matrix heatmap
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Healthy','Failure'], yticklabels=['Healthy','Failure'])
plt.title('Confusion Matrix: Predictive Maintanance Model')
plt.ylabel('Actual Label')
plt.xlabel('Predicted Label')
plt.tight_layout()
plt.savefig('plots/confusion_matrix.png')
#plt.close()
plt.show()

# Feature Importance Graph
importances= model.feature_importances_
features= X.columns
indices= np.argsort(importances)[::-1]

plt.figure(figsize=(8,6))
sns.barplot(
    x=importances[indices],
    y=features[indices],
    hue= features[indices],
    palette='viridis',
    legend=False
)
plt.title('Feature Importances in Explaining Machine Failures')
plt.xlabel('Relative Importance Score')
plt.ylabel('Features')
plt.tight_layout()
plt.savefig('plots/features_importances.png')
plt.show()